### ISSUE TITLE
Doesn't work at all except for -e

### ISSUE THREAD

**Issue by kokizzu** [goruby/goruby#1]
`goruby anythingthatdoesntexists.rb` --> no error

`goruby anythingthatexists.rb` --> no output
`goruby ./anythingthatexists.rb` --> no output
`goruby `pwd`/anythingthatexists.rb` --> no output
`cat anythingthatexists.rb | goruby` --> no output

`gourby -v=true` --> no output

`goruby --version` --> at last.. an output:

```
flag provided but not defined: -version
Usage of goruby:
  -e="": one line of script. Several -e's allowed. Omit [programfile]
  -v=false: print version number, then turn on verbose mode
```

`goruby -e="puts 1+1"` --> gives `2`
`

**Comment by mitch000001** [comment]
Hey, unfortunately there is no working implementation yet. I spiked on some local branches how to transform the parse.y file of MRI ruby, but progress is slow. I will try to find the time to add at least a disclaimer on the current state of this project.

**Comment by shizeeg** [comment]
@kokizzu you might like to give https://crystal-lang.org/ a try if you like Ruby-like languages.

**Comment by skx** [comment]
Since loading files via the command-line now works as expected, this can probably be closed.

:)
