### ISSUE TITLE
`$:` missing

### ISSUE THREAD

**Issue by mitch000001** [goruby/goruby#43]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/401208/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/401208"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9q/wtg2gqwd57x88fy6qw79klsn6zl9w9/T/go-build841597827=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What version of GoRuby are you using (git show -s --format=%H or goruby -version)?
```bash
git show -s --format=%H
# => 07b0c0a9b40cc6551c20cc830965e315ab61c803
```
### What did you do?

```bash
go run main.go -e 'puts $:.nil?'
```

### What did you expect to see?
```bash
false
```

### What did you see instead?
```bash

```

**Comment by skx** [comment]
This appears to be fixed now:

      frodo ~/go/src/github.com/goruby/goruby $ git show -s --format=%H
      ee5b7274d84c124a2bd3b3d6f1e2c78d31148cc5

Sample run:

       frodo ~/go/src/github.com/goruby/goruby $ go run main.go -e 'puts $:.nil?'
       false
